# Generated by Django 3.1.7 on 2021-04-13 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neighbour', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='neighbourhood',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='neighbour.neighbourhood'),
        ),
    ]
